name: harvest_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: 3.4.0
  stacked_services: 1.1.0
  google_fonts: 6.2.1
  flutter_svg: 1.1.6

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

harvest_assets: &harvest_assets
  - packages/harvest_app/assets/images/google.png
  - packages/harvest_app/assets/images/avatar.png
  - packages/harvest_app/assets/images/tree.png
  - packages/harvest_app/assets/images/map.png
  # icons
  - packages/harvest_app/assets/icons/map.svg
  - packages/harvest_app/assets/icons/map-pin.svg

flutter:
  uses-material-design: true
  assets: *harvest_assets
